name: Loan_prediction
channels:
  - defaults

dependencies:
  - python=3.10.13
  - pip<=23.2.1
  - pip:
    - mlflow==2.7.1
    - cloudpickle==2.2.1
    - numpy==1.26.0
    - packaging==23.1
    - pyyaml==6.0.1
    - scikit-learn==1.3.0
    - scipy==1.11.2